export const CookieWindow = '[class="body style-scope ytd-consent-bump-v2-lightbox"]'
export const DeclineCookie = 'div.eom-button-row:nth-child(1) > ytd-button-renderer:nth-child(1) > yt-button-shape:nth-child(1) > button:nth-child(1) > div:nth-child(1)'
export const Account = '[id="sign-in-button"]'
export const SignInEmail = '[id="identifierId"]'
export const NextButtonSignIn = '[jsname="V67aGc"]'