export const CookieWindow = '[class="body style-scope ytd-consent-bump-v2-lightbox"]'
export const DeclineCookie = 'div.eom-button-row:nth-child(1) > ytd-button-renderer:nth-child(1) > yt-button-shape:nth-child(1) > button:nth-child(1) > div:nth-child(1)'
export const Account = 'ytd-button-renderer.ytd-masthead:nth-child(2) > yt-button-shape:nth-child(1) > a:nth-child(1) > yt-touch-feedback-shape:nth-child(3) > div:nth-child(1) > div:nth-child(2)'
export const SignInEmail = '[id="identifierId"]'
export const NextButtonSignIn = '[id="identifierNext"]'
export const SearchInput = '[id="search"]'
export const SearchButton = '[id="search-icon-legacy"]'
export const SelectVideo = '[title="Playwright Beginner Tutorials"]'
export const SkipADButton = '[class="ytp-ad-text ytp-ad-skip-button-text-centered ytp-ad-skip-button-text"]'